"""Agent (SIP user) management.

Agents are SIP accounts that log in from a softphone (Zoiper/PortSIP) to take
the transferred calls. They are managed dynamically from the Telegram bot:

* the store keeps an index (JSON),
* renders a PJSIP include file that Asterisk loads (``#tryinclude``),
* asks Asterisk to ``pjsip reload`` through AMI after every change.

Each agent has a provisioning token so Zoiper can auto-configure via QR.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import secrets
import time
from dataclasses import asdict, dataclass
from xml.sax.saxutils import escape

from .ami import AMIClient

logger = logging.getLogger(__name__)


def _slug(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "", name.lower())
    return s[:12] or "agente"


def _gen_password() -> str:
    # Readable, URL-safe, no ambiguous characters.
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789"
    return "".join(secrets.choice(alphabet) for _ in range(12))


@dataclass
class Agent:
    id: str
    name: str
    sip_user: str
    sip_password: str
    token: str
    created: float


class AgentStore:
    def __init__(self, store_path: str, include_path: str, ami: AMIClient,
                 sip_transport: str = "transport-udp"):
        self.store_path = store_path
        self.include_path = include_path
        self.ami = ami
        self.sip_transport = sip_transport
        self._items: dict[str, Agent] = {}
        self._lock = asyncio.Lock()
        os.makedirs(os.path.dirname(store_path) or ".", exist_ok=True)
        os.makedirs(os.path.dirname(include_path) or ".", exist_ok=True)
        self._load()

    # --------------------------------------------------------------- persistence
    def _load(self) -> None:
        if not os.path.exists(self.store_path):
            return
        try:
            with open(self.store_path, encoding="utf-8") as fh:
                data = json.load(fh)
            for raw in data.get("agents", []):
                ag = Agent(**raw)
                self._items[ag.id] = ag
        except Exception:  # noqa: BLE001
            logger.exception("Could not load agents index; starting empty")

    def _save(self) -> None:
        tmp = self.store_path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump({"agents": [asdict(a) for a in self._items.values()]}, fh,
                      ensure_ascii=False, indent=2)
        os.replace(tmp, self.store_path)

    # --------------------------------------------------------------- queries
    def list(self) -> list[Agent]:
        return sorted(self._items.values(), key=lambda a: a.created)

    def get(self, agent_id: str) -> Agent | None:
        return self._items.get(agent_id)

    def by_token(self, token: str) -> Agent | None:
        for a in self._items.values():
            if a.token == token:
                return a
        return None

    def endpoints(self) -> list[str]:
        """PJSIP endpoint dial strings for all agents (ring group)."""
        return [f"PJSIP/{a.sip_user}" for a in self._items.values()]

    # --------------------------------------------------------------- rendering
    def _render_include(self) -> str:
        blocks = [
            "; Generated by Piensa Dialer — do not edit by hand.",
            "; SIP agent accounts (Zoiper/PortSIP). Reloaded via AMI.",
            "",
        ]
        for a in self._items.values():
            u = a.sip_user
            blocks.append(
                f"[{u}]\n"
                f"type = endpoint\n"
                f"transport = {self.sip_transport}\n"
                f"context = from-agents\n"
                f"disallow = all\n"
                f"allow = alaw,ulaw,g722,opus\n"
                f"auth = {u}-auth\n"
                f"aors = {u}\n"
                f"direct_media = no\n"
                f"rtp_symmetric = yes\n"
                f"force_rport = yes\n"
                f"rewrite_contact = yes\n"
                f"callerid = {a.name} <{u}>\n"
            )
            blocks.append(
                f"[{u}-auth]\n"
                f"type = auth\n"
                f"auth_type = userpass\n"
                f"username = {u}\n"
                f"password = {a.sip_password}\n"
            )
            blocks.append(
                f"[{u}]\n"
                f"type = aor\n"
                f"max_contacts = 3\n"
                f"remove_existing = yes\n"
                f"qualify_frequency = 30\n"
            )
        return "\n".join(blocks) + "\n"

    async def _apply(self) -> None:
        tmp = self.include_path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(self._render_include())
        os.replace(tmp, self.include_path)
        await self.ami.reload_pjsip()

    # --------------------------------------------------------------- mutations
    async def create(self, name: str) -> Agent:
        async with self._lock:
            base = _slug(name)
            user = base
            n = 1
            existing = {a.sip_user for a in self._items.values()}
            while user in existing:
                n += 1
                user = f"{base}{n}"
            agent = Agent(
                id=secrets.token_hex(4),
                name=name[:40] or user,
                sip_user=user,
                sip_password=_gen_password(),
                token=secrets.token_urlsafe(12),
                created=time.time(),
            )
            self._items[agent.id] = agent
            self._save()
            await self._apply()
        logger.info("Created agent %s (%s)", agent.sip_user, agent.id)
        return agent

    async def delete(self, agent_id: str) -> bool:
        async with self._lock:
            if agent_id not in self._items:
                return False
            self._items.pop(agent_id)
            self._save()
            await self._apply()
            return True

    async def ensure_seed(self, sip_user: str, sip_password: str, name: str = "Agente 1") -> None:
        """Create a first agent from env credentials if the store is empty."""
        async with self._lock:
            if self._items:
                return
            if not sip_user or not sip_password:
                return
            agent = Agent(
                id=secrets.token_hex(4),
                name=name,
                sip_user=sip_user,
                sip_password=sip_password,
                token=secrets.token_urlsafe(12),
                created=time.time(),
            )
            self._items[agent.id] = agent
            self._save()
            await self._apply()
            logger.info("Seeded default agent %s", sip_user)

    # --------------------------------------------------------------- provisioning
    def provisioning_xml(self, agent: Agent, sip_domain: str, transport: int = 0) -> str:
        """Zoiper5-compatible provisioning XML for one account.

        ``transport``: 0=UDP, 1=TCP, 2=TLS.
        """
        return (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            "<options>\n"
            "  <prov_version>1.14</prov_version>\n"
            f"  <prov_id>{escape(agent.token)}</prov_id>\n"
            f"  <prov_name>{escape(agent.name)}</prov_name>\n"
            "  <accounts>\n"
            "    <account>\n"
            f"      <ident>{escape(agent.id)}</ident>\n"
            f"      <name>{escape(agent.name)}</name>\n"
            f"      <username>{escape(agent.sip_user)}</username>\n"
            f"      <password>{escape(agent.sip_password)}</password>\n"
            f"      <host>{escape(sip_domain)}</host>\n"
            f"      <SIP_domain>{escape(sip_domain)}</SIP_domain>\n"
            "      <SIP_use_auth_username>true</SIP_use_auth_username>\n"
            f"      <SIP_auth_username>{escape(agent.sip_user)}</SIP_auth_username>\n"
            f"      <transport_type>{transport}</transport_type>\n"
            "      <register_on_startup>true</register_on_startup>\n"
            "      <enabled>true</enabled>\n"
            "    </account>\n"
            "  </accounts>\n"
            "</options>\n"
        )
