! Cisco SIP phone profile generated by SMURF
voice service voip
 sip
  registrar server expires max 3600 min 60
!
line 1
 description "{DISPLAY_NAME}"
 name "{EXTENSION}"
 authname "{AUTH_USER}"
 password "{AUTH_PASS}"
 transport udp
 proxy "{SIP_SERVER}:{SIP_UDP_PORT}"
!
