# Polycom provisioning generated by SMURF
[reg.1]
address={EXTENSION}
label={DISPLAY_NAME}
auth.userId={AUTH_USER}
auth.password={AUTH_PASS}
server.1.address={SIP_SERVER}
server.1.port={SIP_UDP_PORT}
server.1.transport=UDPOnly
